networks:
  example-kafka-app-network:
    driver: bridge

services:
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    container_name: kafka
    networks:
      - example-kafka-app-network
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - '9092:9092'
      - '9093:9093'
      - '9094:9094'
  producer:
    image: $IMAGE_NAMESPACE/$PRODUCER_IMAGE_NAME:$VER
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - example-kafka-app-network
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: 'example_topic'
  consumer:
    image: $IMAGE_NAMESPACE/$CONSUMER_IMAGE_NAME:$VER
    networks:
      - example-kafka-app-network
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: 'example_topic'